
/*
 * Login.java
 * Autor: Hernández Paredes Denis Alin
 * Created on 5/05/2011, 10:47:59 AM
 */
package gestionordenesliquidacion;

import javax.swing.*;
import Common.*;
import java.sql.*;

public class Login extends javax.swing.JFrame {

    //Variable que almacena el usuario que inicio sesion
    public static String user = "";

    /** Creates new form Login */
    public Login() {
        initComponents();
        this.mitxtUsuario.grabFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mitxtUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mitxtPassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Validación de Usuario");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(202, 227, 127));
        jPanel1.setLayout(null);

        mitxtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(mitxtUsuario);
        mitxtUsuario.setBounds(150, 80, 160, 30);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 170, 73, 23);

        mitxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(mitxtPassword);
        mitxtPassword.setBounds(150, 110, 160, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(47, 113, 148));
        jLabel12.setText("Password:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 110, 80, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(47, 113, 148));
        jLabel13.setText("Usuario:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 80, 70, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 230);

        setSize(new java.awt.Dimension(415, 258));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mitxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtUsuarioActionPerformed
        this.mitxtPassword.grabFocus();
    }//GEN-LAST:event_mitxtUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario = this.mitxtUsuario.getText().toString().trim();
        String password = this.mitxtPassword.getText().toString().trim();
        
        String[] valido = this.validaUsuario(usuario, password);

        if (valido!=null) {
            Login.user = usuario;
            Usuario userApp;
            userApp = new Usuario(valido[0],valido[1],valido[2]);
            new Menu().show();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, " Usuario / Password Inválidos ", "Error", JOptionPane.ERROR_MESSAGE);
            this.mitxtUsuario.setText("");
            this.mitxtPassword.setText("");
            this.mitxtUsuario.grabFocus();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void mitxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtPasswordActionPerformed
        this.jButton1.grabFocus();
    }//GEN-LAST:event_mitxtPasswordActionPerformed

    public String[] validaUsuario(String usuario, String password) {

        clsConexion conn = new clsConexion();
        Connection connection = null;
        Statement statement = null;

        String[] valido = null;
        String MySql = "";
        try {
            connection = conn.ConectaSQLServer();
            statement = connection.createStatement();
            statement.execute("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED");
            
            MySql = " select usuario,tipo_cuenta,correo ";
            MySql += " from usuarios_admin ";
            MySql += " where usuario='" + usuario + "' ";
            MySql += " and password='" + password + "' ";

            ResultSet rstSQLServer = statement.executeQuery(MySql);

            if (rstSQLServer.next()) {  
                valido = new String[3];
                valido[0] = rstSQLServer.getString(1).trim();
                valido[1] = rstSQLServer.getString(2).trim();
                valido[2] = rstSQLServer.getString(3).trim();
            }
            rstSQLServer.close();
            statement.close();

            if (connection != null) {
                conn.Desconecta(connection);
            }
        } catch (Exception e) {
            System.out.println("Exception-validaUsuario"+ e.getMessage());
        }
        return valido;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField mitxtPassword;
    private javax.swing.JTextField mitxtUsuario;
    // End of variables declaration//GEN-END:variables
}
