
/*
 * Menu.java
 *Autor : Hernández Paredes Denis Alin
 * Created on 5/05/2011, 11:20:18 AM
 */
package gestionordenesliquidacion;

import GestionUsuarios.*;
import GestionContratos.*;
import GestionCuentasBancarias.*;
import Common.clsILookAndFeel;
import gestionordenesliquidacion.Usuario;

public class Menu extends javax.swing.JFrame {

    /** Creates new form Menu */
    public Menu() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        mibtnBaja = new javax.swing.JButton();
        mibtnAlta = new javax.swing.JButton();
        mibtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Liquidaciones");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(202, 227, 127));
        jPanel1.setLayout(null);

        jToolBar3.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar3.setFloatable(false);
        jToolBar3.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar3.setRollover(true);
        jToolBar3.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar3.setPreferredSize(new java.awt.Dimension(500, 47));

        mibtnBaja.setBackground(new java.awt.Color(255, 255, 255));
        mibtnBaja.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnBaja.setForeground(new java.awt.Color(255, 255, 255));
        mibtnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/contrato01.jpg"))); // NOI18N
        mibtnBaja.setToolTipText("Gestión de Contratos");
        mibtnBaja.setFocusPainted(false);
        mibtnBaja.setFocusable(false);
        mibtnBaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnBaja.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mibtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnBajaActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnBaja);

        mibtnAlta.setBackground(new java.awt.Color(255, 255, 255));
        mibtnAlta.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnAlta.setForeground(new java.awt.Color(255, 255, 255));
        mibtnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/usuarios.jpg"))); // NOI18N
        mibtnAlta.setToolTipText("Gestión de Usuarios");
        mibtnAlta.setFocusPainted(false);
        mibtnAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnAlta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mibtnAlta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnAltaActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnAlta);

        mibtnSalir.setBackground(new java.awt.Color(204, 204, 204));
        mibtnSalir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        mibtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/dinero.jpg"))); // NOI18N
        mibtnSalir.setToolTipText("Gestión de Cuentas Bancarias");
        mibtnSalir.setFocusPainted(false);
        mibtnSalir.setFocusable(false);
        mibtnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnSalir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnSalirActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnSalir);

        jPanel1.add(jToolBar3);
        jToolBar3.setBounds(140, 100, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -20, 410, 190);

        setSize(new java.awt.Dimension(427, 209));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mibtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnAltaActionPerformed
        new clsGestionUsuarios().show();
    }//GEN-LAST:event_mibtnAltaActionPerformed

    private void mibtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnBajaActionPerformed
        new GestionContratos().show();
}//GEN-LAST:event_mibtnBajaActionPerformed

    private void mibtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnSalirActionPerformed
        new gestionCuentas().show();
}//GEN-LAST:event_mibtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {                
                clsILookAndFeel.setSystemLookAndFell();
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JButton mibtnAlta;
    private javax.swing.JButton mibtnBaja;
    private javax.swing.JButton mibtnSalir;
    // End of variables declaration//GEN-END:variables
}
