
/*
 * GestionContratos.java
 * Autor : Hernández Paredes Denis Alin
 * Created on 13/04/2011, 05:01:13 PM
 */
package GestionContratos;

import Common.clsILookAndFeel;
import gestionordenesliquidacion.Menu;
import javax.swing.JOptionPane;

public class GestionContratos extends javax.swing.JFrame {

    /** Creates new form GestionContratos */
    public GestionContratos() {
        initComponents();       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        mibtnAlta = new javax.swing.JButton();
        mibtnBaja = new javax.swing.JButton();
        mibtnSalir = new javax.swing.JButton();
        mibtnReporte = new javax.swing.JButton();
        milblTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Contratos");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(201, 226, 126));
        jPanel1.setLayout(null);

        jToolBar3.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar3.setFloatable(false);
        jToolBar3.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar3.setRollover(true);
        jToolBar3.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar3.setPreferredSize(new java.awt.Dimension(500, 47));

        mibtnAlta.setBackground(new java.awt.Color(255, 255, 255));
        mibtnAlta.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnAlta.setForeground(new java.awt.Color(255, 255, 255));
        mibtnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/alta_contrato.jpg"))); // NOI18N
        mibtnAlta.setToolTipText("Alta de Contrato");
        mibtnAlta.setFocusPainted(false);
        mibtnAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnAlta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mibtnAlta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnAltaActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnAlta);

        mibtnBaja.setBackground(new java.awt.Color(255, 255, 255));
        mibtnBaja.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnBaja.setForeground(new java.awt.Color(255, 255, 255));
        mibtnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/baja_contrato.jpg"))); // NOI18N
        mibtnBaja.setToolTipText("Baja de Contrato");
        mibtnBaja.setFocusPainted(false);
        mibtnBaja.setFocusable(false);
        mibtnBaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnBaja.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mibtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnBajaActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnBaja);

        mibtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        mibtnSalir.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        mibtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/modificar.jpg"))); // NOI18N
        mibtnSalir.setToolTipText("Modificar Contrato");
        mibtnSalir.setFocusPainted(false);
        mibtnSalir.setFocusable(false);
        mibtnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnSalir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnSalirActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnSalir);

        mibtnReporte.setBackground(new java.awt.Color(255, 255, 255));
        mibtnReporte.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnReporte.setForeground(new java.awt.Color(255, 255, 255));
        mibtnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Tabla.jpg"))); // NOI18N
        mibtnReporte.setToolTipText("Consulta de Contrato");
        mibtnReporte.setFocusable(false);
        mibtnReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        mibtnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnReporte.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mibtnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnReporteActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnReporte);

        jPanel1.add(jToolBar3);
        jToolBar3.setBounds(120, 100, 150, 40);

        milblTitulo1.setBackground(new java.awt.Color(0, 51, 153));
        milblTitulo1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        milblTitulo1.setForeground(new java.awt.Color(47, 113, 148));
        milblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milblTitulo1.setText("ADMINISTRACIÓN DE CONTRATOS");
        jPanel1.add(milblTitulo1);
        milblTitulo1.setBounds(0, 40, 400, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -20, 400, 180);

        setSize(new java.awt.Dimension(416, 198));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mibtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnSalirActionPerformed
        new mntnModificacionContratos().show();
}//GEN-LAST:event_mibtnSalirActionPerformed

    private void mibtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnAltaActionPerformed
        if(gestionordenesliquidacion.Usuario.userApp.getTipo_cuenta().equals("ADM")){
        new mntnAltaContratos().show();
        }
        else{
        JOptionPane.showMessageDialog(this, "Necesita privilegio de administrador para realizar esta operación.", "Usuario sin privilegios", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_mibtnAltaActionPerformed

    private void mibtnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnReporteActionPerformed
        new rprtContratos().show();
}//GEN-LAST:event_mibtnReporteActionPerformed

    private void mibtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnBajaActionPerformed
        new mntnBajaContratos().show();
    }//GEN-LAST:event_mibtnBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new GestionContratos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JButton mibtnAlta;
    private javax.swing.JButton mibtnBaja;
    private javax.swing.JButton mibtnReporte;
    private javax.swing.JButton mibtnSalir;
    private javax.swing.JLabel milblTitulo1;
    // End of variables declaration//GEN-END:variables
}
