/*
 * mntnAltaContratos.java
 *
 * Created on 13/04/2011, 10:08:46 AM
 */
package GestionContratos;

import javax.swing.*;
import Common.clsILookAndFeel;

//import java.util.Locale;

import java.util.Vector;

public class mntnAltaContratos extends javax.swing.JFrame {

    clsModelo c = new clsModelo();

    /** Creates new form mntnAltaContratos */
    public mntnAltaContratos() {
        initComponents();
        Limpia();
        this.mitxtClaveContrato.grabFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        milblTitulo = new javax.swing.JLabel();
        mitxtClaveContrato = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        mitxtNombreCliente = new javax.swing.JTextField();
        mitxtOficinas = new javax.swing.JTextField();
        mitxtGrupo = new javax.swing.JTextField();
        mitxtDomicilioFiscal = new javax.swing.JTextField();
        mitxtRFC = new javax.swing.JTextField();
        mitxtTel = new javax.swing.JTextField();
        mitxtHonorarioSinIVA = new javax.swing.JTextField();
        mitxtHonorario = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        mitxtCorreo = new javax.swing.JTextField();
        mitxtCuentaOrigen = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        mitxtID_codes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Captura de Contratos");
        getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("CLAVE CONTRATO");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 120, 140, 30);

        jButton.setText("Guardar");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        jButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonKeyPressed(evt);
            }
        });
        getContentPane().add(jButton);
        jButton.setBounds(310, 540, 80, 20);

        milblTitulo.setBackground(new java.awt.Color(0, 51, 153));
        milblTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        milblTitulo.setForeground(new java.awt.Color(47, 113, 148));
        milblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milblTitulo.setText(" ALTA DE CONTRATOS");
        getContentPane().add(milblTitulo);
        milblTitulo.setBounds(0, 50, 680, 40);

        mitxtClaveContrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtClaveContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtClaveContratoActionPerformed(evt);
            }
        });
        getContentPane().add(mitxtClaveContrato);
        mitxtClaveContrato.setBounds(170, 120, 200, 30);

        jToolBar2.setBackground(new java.awt.Color(202, 227, 127));
        jToolBar2.setBorder(new javax.swing.border.SoftBevelBorder(0, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(0, 0, 102));
        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar2.setPreferredSize(new java.awt.Dimension(500, 47));
        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(0, 0, 700, 40);

        jCheckBox1.setText("Dar de Alta una Baja");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(430, 110, 140, 23);

        jPanel.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("NOMBRE CLIENTE");
        jPanel.add(jLabel16);
        jLabel16.setBounds(10, 0, 120, 30);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("CUENTA ORIGEN");
        jPanel.add(jLabel17);
        jLabel17.setBounds(10, 30, 120, 30);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("GRUPO");
        jPanel.add(jLabel18);
        jLabel18.setBounds(10, 60, 120, 30);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("DOMICILIO FISCAL");
        jPanel.add(jLabel19);
        jLabel19.setBounds(10, 90, 120, 30);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setText("RFC");
        jPanel.add(jLabel20);
        jLabel20.setBounds(10, 120, 120, 30);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setText("TELÉFONO");
        jPanel.add(jLabel21);
        jLabel21.setBounds(10, 150, 120, 30);

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("TIPO HONORARIO");
        jPanel.add(jLabel22);
        jLabel22.setBounds(10, 210, 120, 30);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setText("HONORARIO SIN IVA");
        jPanel.add(jLabel23);
        jLabel23.setBounds(10, 240, 140, 30);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setText("OFICINAS");
        jPanel.add(jLabel24);
        jLabel24.setBounds(10, 270, 120, 30);

        mitxtNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtNombreClienteActionPerformed(evt);
            }
        });
        jPanel.add(mitxtNombreCliente);
        mitxtNombreCliente.setBounds(150, 0, 490, 30);

        mitxtOficinas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtOficinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtOficinasActionPerformed(evt);
            }
        });
        jPanel.add(mitxtOficinas);
        mitxtOficinas.setBounds(150, 270, 200, 30);

        mitxtGrupo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtGrupoActionPerformed(evt);
            }
        });
        jPanel.add(mitxtGrupo);
        mitxtGrupo.setBounds(150, 60, 200, 30);

        mitxtDomicilioFiscal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtDomicilioFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtDomicilioFiscalActionPerformed(evt);
            }
        });
        jPanel.add(mitxtDomicilioFiscal);
        mitxtDomicilioFiscal.setBounds(150, 90, 200, 30);

        mitxtRFC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtRFCActionPerformed(evt);
            }
        });
        jPanel.add(mitxtRFC);
        mitxtRFC.setBounds(150, 120, 200, 30);

        mitxtTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtTelActionPerformed(evt);
            }
        });
        jPanel.add(mitxtTel);
        mitxtTel.setBounds(150, 150, 200, 30);

        mitxtHonorarioSinIVA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtHonorarioSinIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtHonorarioSinIVAActionPerformed(evt);
            }
        });
        jPanel.add(mitxtHonorarioSinIVA);
        mitxtHonorarioSinIVA.setBounds(150, 240, 200, 30);

        mitxtHonorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtHonorarioActionPerformed(evt);
            }
        });
        jPanel.add(mitxtHonorario);
        mitxtHonorario.setBounds(150, 210, 200, 30);

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setText("E-MAIL ASESOR");
        jPanel.add(jLabel25);
        jLabel25.setBounds(10, 180, 130, 30);

        mitxtCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mitxtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtCorreoActionPerformed(evt);
            }
        });
        jPanel.add(mitxtCorreo);
        mitxtCorreo.setBounds(150, 180, 200, 30);

        mitxtCuentaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtCuentaOrigenActionPerformed(evt);
            }
        });
        jPanel.add(mitxtCuentaOrigen);
        mitxtCuentaOrigen.setBounds(150, 30, 200, 30);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("ID_CODES");
        jPanel.add(jLabel1);
        jLabel1.setBounds(10, 300, 90, 30);

        mitxtID_codes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtID_codesActionPerformed(evt);
            }
        });
        jPanel.add(mitxtID_codes);
        mitxtID_codes.setBounds(150, 300, 200, 30);

        getContentPane().add(jPanel);
        jPanel.setBounds(20, 150, 650, 360);

        setSize(new java.awt.Dimension(698, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void Limpia() {
        Vector tmp = new Vector();
        tmp.add("    ------------ Selecciona ------------  ");
        tmp.add("RIESGOS");
        tmp.add("PATRIMONIO");
        this.mitxtClaveContrato.setText("");
        this.mitxtNombreCliente.setText("");
        this.mitxtCuentaOrigen.setModel(new DefaultComboBoxModel(clsModelo.getCuentaOrigen()));
        this.mitxtGrupo.setText("");
        this.mitxtDomicilioFiscal.setText("");
        this.mitxtRFC.setText("");
        this.mitxtTel.setText("");
        this.mitxtCorreo.setText("");
        this.mitxtHonorarioSinIVA.setText("");
        this.mitxtHonorario.setModel(new DefaultComboBoxModel(tmp));
        this.mitxtOficinas.setText("");
        this.mitxtID_codes.setText("");
    }

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        String mitxtClaveContrato = this.mitxtClaveContrato.getText().toUpperCase().toString().trim();
        String mitxtNombreCliente = this.mitxtNombreCliente.getText().toUpperCase().toString().trim();
        String mitxtCuentaOrigen = this.mitxtCuentaOrigen.getSelectedItem().toString();
        String mitxtGrupo = this.mitxtGrupo.getText().toUpperCase().toString().trim();
        String mitxtDomicilioFiscal = this.mitxtDomicilioFiscal.getText().toUpperCase().toString().trim();
        String mitxtRFC = this.mitxtRFC.getText().toUpperCase().toString().trim();
        String mitxtTel = this.mitxtTel.getText().toUpperCase().toString().trim();
        String correo = this.mitxtCorreo.getText().toUpperCase().toString().trim();
        String mitxtHonorario = this.mitxtHonorario.getSelectedItem().toString();
        String honorario_sin_iva = this.mitxtHonorarioSinIVA.getText().toString().trim();
        String mitxtOficinas = this.mitxtOficinas.getText().toUpperCase().toString().trim();
        String mitxtID_codes = this.mitxtID_codes.getText().toUpperCase().toString().trim();
        boolean miCheckBox = jCheckBox1.isSelected();
        boolean seGuardo = false;
        if (miCheckBox) {
            if (!mitxtClaveContrato.equals("")) {
                seGuardo = c.activaContrato(mitxtClaveContrato);
                if (seGuardo) {
                    JOptionPane.showMessageDialog(this, " Operación realizada satisfactoriamente ", "Información", JOptionPane.INFORMATION_MESSAGE);
                    Limpia();
                    this.mitxtClaveContrato.grabFocus();
                } else {
                    JOptionPane.showMessageDialog(this, " Error actualizando contrato ", "Error", JOptionPane.ERROR_MESSAGE);
                    Limpia();
                    this.mitxtClaveContrato.grabFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, " Favor de especificar clave de contrato ", "Alerta", JOptionPane.WARNING_MESSAGE);
                this.mitxtClaveContrato.grabFocus();
            }
        } else {

            if (!mitxtCuentaOrigen.equals("    ------------ Selecciona ------------  ") && !mitxtHonorario.equals("    ------------ Selecciona ------------  ")) {
                if (!mitxtClaveContrato.equals("") && !mitxtNombreCliente.equals("") && !mitxtCuentaOrigen.equals("") && !mitxtGrupo.equals("")
                        && !mitxtDomicilioFiscal.equals("") && !mitxtRFC.equals("") && !mitxtHonorario.equals("")
                        && !honorario_sin_iva.equals("") && !mitxtID_codes.equals("") ) {

                    seGuardo = c.guardaContrato(mitxtClaveContrato, mitxtNombreCliente, mitxtCuentaOrigen, mitxtGrupo,
                            mitxtDomicilioFiscal, mitxtRFC, mitxtTel, correo, mitxtHonorario,
                            honorario_sin_iva, mitxtOficinas, mitxtID_codes);
                    if (seGuardo) {
                        JOptionPane.showMessageDialog(this, " Operación realizada satisfactoriamente ", "Información", JOptionPane.INFORMATION_MESSAGE);
                        Limpia();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error almacenando información", "Error", JOptionPane.ERROR_MESSAGE);
                        this.mitxtClaveContrato.grabFocus();
                        Limpia();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Información incompleta, favor de verificar", "Alerta", JOptionPane.WARNING_MESSAGE);
                    this.mitxtClaveContrato.grabFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Favor de especificar cuenta de origen y/o tipo de honorario ", "Alerta", JOptionPane.WARNING_MESSAGE);
                this.mitxtCuentaOrigen.grabFocus();
            }

        }

    }//GEN-LAST:event_jButtonActionPerformed

    private void mitxtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtNombreClienteActionPerformed
        String nombre_cliente = this.mitxtNombreCliente.getText().toString().trim();
//        System.out.println(nombre_cliente.ge);
        if (!nombre_cliente.equals("")) {
            this.mitxtCuentaOrigen.grabFocus();
        } else {
            JOptionPane.showMessageDialog(this, " Nombre del fideicomitente obligatorio ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.mitxtNombreCliente.grabFocus();
        }

}//GEN-LAST:event_mitxtNombreClienteActionPerformed

    private void mitxtOficinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtOficinasActionPerformed
        this.jButton.grabFocus();
    }//GEN-LAST:event_mitxtOficinasActionPerformed

    private void mitxtClaveContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtClaveContratoActionPerformed
        String clave_contrato = this.mitxtClaveContrato.getText().toUpperCase().toString().trim();
        boolean miCheckBox = jCheckBox1.isSelected();
        boolean existe = false;
        if (!clave_contrato.equals("")) {
            if (miCheckBox) {
                existe = c.esContratoInactivo(clave_contrato);
                if (existe) {
                    this.jButton.grabFocus();
                } else {
                    JOptionPane.showMessageDialog(this, " El contrato NO se encuentra registrado Como BAJA ", "Alerta", JOptionPane.WARNING_MESSAGE);
                    this.mitxtClaveContrato.grabFocus();
                }
            } else {
                existe = c.verificaContrato(clave_contrato);
                boolean clave_valida = false;
                if (existe) {
                    JOptionPane.showMessageDialog(this, " Clave de contrato existente ", "Alerta", JOptionPane.WARNING_MESSAGE);
                    this.mitxtClaveContrato.setText("");
                    this.mitxtClaveContrato.grabFocus();
                } else {
                    clave_valida = c.validaClaveContrato(clave_contrato);
                    if (clave_valida) {
                        this.mitxtNombreCliente.grabFocus();
                    } else {
                        JOptionPane.showMessageDialog(this, " Clave inválida, favor de verificar ", "Error", JOptionPane.ERROR_MESSAGE);
                        this.mitxtClaveContrato.grabFocus();
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, " Clave de contrato obligatoria ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.mitxtClaveContrato.grabFocus();
        }
    }//GEN-LAST:event_mitxtClaveContratoActionPerformed

    private void mitxtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtGrupoActionPerformed
        String grupo = this.mitxtGrupo.getText().toString().trim();
        if (!grupo.equals("")) {
            this.mitxtDomicilioFiscal.grabFocus();
        } else {
            JOptionPane.showMessageDialog(this, " Tipo de contrato obligatorio ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.mitxtGrupo.grabFocus();
        }
    }//GEN-LAST:event_mitxtGrupoActionPerformed

    private void mitxtDomicilioFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtDomicilioFiscalActionPerformed
        String domicilio = this.mitxtDomicilioFiscal.getText().toString().trim();
        if (!domicilio.equals("")) {
            this.mitxtRFC.grabFocus();
        } else {
            JOptionPane.showMessageDialog(this, " Domicilio fiscal obligatorio ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.mitxtDomicilioFiscal.grabFocus();
        }
    }//GEN-LAST:event_mitxtDomicilioFiscalActionPerformed

    private void mitxtRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtRFCActionPerformed

        String rfc = this.mitxtRFC.getText().toString().trim();
        if (!rfc.equals("")) {
            this.mitxtTel.grabFocus();
        } else {
            JOptionPane.showMessageDialog(this, " RFC obligatorio ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.mitxtRFC.grabFocus();
        }
    }//GEN-LAST:event_mitxtRFCActionPerformed

    private void mitxtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtTelActionPerformed
        this.mitxtCorreo.grabFocus();
    }//GEN-LAST:event_mitxtTelActionPerformed

    private void jButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonKeyPressed

        String mitxtClaveContrato = this.mitxtClaveContrato.getText().toUpperCase().toString().trim();
        String mitxtNombreCliente = this.mitxtNombreCliente.getText().toUpperCase().toString().trim();
        String mitxtCuentaOrigen = this.mitxtCuentaOrigen.getSelectedItem().toString();
        String mitxtGrupo = this.mitxtGrupo.getText().toUpperCase().toString().trim();
        String mitxtDomicilioFiscal = this.mitxtDomicilioFiscal.getText().toUpperCase().toString().trim();
        String mitxtRFC = this.mitxtRFC.getText().toUpperCase().toString().trim();
        String mitxtTel = this.mitxtTel.getText().toUpperCase().toString().trim();
        String correo = this.mitxtCorreo.getText().toString().trim();
        String mitxtHonorario = this.mitxtHonorario.getSelectedItem().toString();
        String honorario_sin_iva = this.mitxtHonorarioSinIVA.getText().toString().trim();
        String mitxtOficinas = this.mitxtOficinas.getText().toUpperCase().toString().trim();
        String mitxtID_codes = this.mitxtID_codes.getText().toUpperCase().toString().trim();
        boolean miCheckBox = jCheckBox1.isSelected();
        boolean seGuardo = false;
        if (miCheckBox) {
            if (!mitxtClaveContrato.equals("")) {
                seGuardo = c.activaContrato(mitxtClaveContrato);
                if (seGuardo) {
                    JOptionPane.showMessageDialog(this, " Operación realizada satisfactoriamente ", "Información", JOptionPane.INFORMATION_MESSAGE);
                    Limpia();
                    this.mitxtClaveContrato.grabFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "Error actualizando información", "Error", JOptionPane.ERROR_MESSAGE);
                    Limpia();
                    this.mitxtClaveContrato.grabFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, " Favor de especificar clave de contrato ", "Alerta", JOptionPane.WARNING_MESSAGE);
                this.mitxtClaveContrato.grabFocus();
            }
        } else {

            if (!mitxtCuentaOrigen.equals("    ------------ Selecciona ------------  ") && !mitxtHonorario.equals("    ------------ Selecciona ------------  ")) {
                if (!mitxtClaveContrato.equals("") && !mitxtNombreCliente.equals("") && !mitxtCuentaOrigen.equals("") && !mitxtGrupo.equals("")
                        && !mitxtDomicilioFiscal.equals("") && !mitxtRFC.equals("") && !mitxtHonorario.equals("")
                        && !honorario_sin_iva.equals("")) {

                    seGuardo = c.guardaContrato(mitxtClaveContrato, mitxtNombreCliente, mitxtCuentaOrigen, mitxtGrupo,
                            mitxtDomicilioFiscal, mitxtRFC, mitxtTel, correo, mitxtHonorario,
                            honorario_sin_iva, mitxtOficinas, mitxtID_codes);
                    if (seGuardo) {
                        JOptionPane.showMessageDialog(this, " Operación realizada satisfactoriamente ", "Información", JOptionPane.INFORMATION_MESSAGE);
                        Limpia();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error almacenando información", "Error", JOptionPane.ERROR_MESSAGE);
                        this.mitxtClaveContrato.grabFocus();
                        Limpia();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Información incompleta", "Alerta", JOptionPane.WARNING_MESSAGE);
                    this.mitxtClaveContrato.grabFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, " Favor de especificar cuenta de origen y/o tipo de honorario ", "Alerta", JOptionPane.WARNING_MESSAGE);
                this.mitxtCuentaOrigen.grabFocus();
            }
        }

    }//GEN-LAST:event_jButtonKeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        boolean miCheckBox = jCheckBox1.isSelected();
        if (miCheckBox) {
            Limpia();
            jPanel.setVisible(false);
            mitxtClaveContrato.grabFocus();
        } else {
            Limpia();
            jPanel.setVisible(true);
            mitxtClaveContrato.grabFocus();
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void mitxtHonorarioSinIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtHonorarioSinIVAActionPerformed
        Float val = 0F;
        String honorarioSinIVA = this.mitxtHonorarioSinIVA.getText().toString().trim();

        if (!honorarioSinIVA.equals("")) {
            try {
                val = Float.parseFloat(honorarioSinIVA);
                if (val > 0) {
                    mitxtOficinas.grabFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "El  porcentaje del honorario sin IVA debe ser mayor a 0", "Alerta", JOptionPane.WARNING_MESSAGE);
                    mitxtHonorarioSinIVA.setText("");
                    mitxtHonorarioSinIVA.grabFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Formato de honorario SIN IVA inválido", "Alerta", JOptionPane.WARNING_MESSAGE);
                mitxtHonorarioSinIVA.setText("");
                mitxtHonorarioSinIVA.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, " Favor de especificar honorario SIN IVA ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.mitxtHonorarioSinIVA.grabFocus();
        }

    }//GEN-LAST:event_mitxtHonorarioSinIVAActionPerformed

    private void mitxtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtCorreoActionPerformed
        String correo = this.mitxtCorreo.getText().toString().trim();
        if (!correo.equals("")) {
            if (correo.contains("@")) {
                this.mitxtHonorario.grabFocus();
            } else {
                JOptionPane.showMessageDialog(this, " Correo inválido ", "Alerta", JOptionPane.WARNING_MESSAGE);
                this.mitxtCorreo.setText("");
                this.mitxtCorreo.grabFocus();
            }
        } else {
            this.mitxtHonorario.grabFocus();
        }
    }//GEN-LAST:event_mitxtCorreoActionPerformed

    private void mitxtCuentaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtCuentaOrigenActionPerformed
        this.mitxtGrupo.grabFocus();
    }//GEN-LAST:event_mitxtCuentaOrigenActionPerformed

    private void mitxtHonorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtHonorarioActionPerformed
        this.mitxtHonorarioSinIVA.grabFocus();
    }//GEN-LAST:event_mitxtHonorarioActionPerformed

    private void mitxtID_codesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtID_codesActionPerformed
        // TODO add your handling code here:
        this.mitxtID_codes.grabFocus();
    }//GEN-LAST:event_mitxtID_codesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new mntnAltaContratos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel milblTitulo;
    private javax.swing.JTextField mitxtClaveContrato;
    private javax.swing.JTextField mitxtCorreo;
    private javax.swing.JComboBox mitxtCuentaOrigen;
    private javax.swing.JTextField mitxtDomicilioFiscal;
    private javax.swing.JTextField mitxtGrupo;
    private javax.swing.JComboBox mitxtHonorario;
    private javax.swing.JTextField mitxtHonorarioSinIVA;
    private javax.swing.JTextField mitxtID_codes;
    private javax.swing.JTextField mitxtNombreCliente;
    private javax.swing.JTextField mitxtOficinas;
    private javax.swing.JTextField mitxtRFC;
    private javax.swing.JTextField mitxtTel;
    // End of variables declaration//GEN-END:variables
}
