/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mntnBajaContratos.java
 *
 * Created on 14/04/2011, 01:26:08 PM
 */
package GestionContratos;

import javax.swing.*;
import Common.clsILookAndFeel;

/**
 *
 * @author SISTEMASGP
 */
public class mntnBajaContratos extends javax.swing.JFrame {

    clsModelo c = new clsModelo();

    /** Creates new form mntnBajaContratos */
    public mntnBajaContratos() {
        initComponents();
        this.jComboBox.setModel(new DefaultComboBoxModel(c.getClientes()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        milblTitulo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja de Contratos");
        getContentPane().setLayout(null);

        jToolBar2.setBackground(new java.awt.Color(202, 227, 127));
        jToolBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(0, 0, 102));
        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar2.setPreferredSize(new java.awt.Dimension(500, 47));
        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(0, 0, 610, 40);

        milblTitulo.setBackground(new java.awt.Color(0, 51, 153));
        milblTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 21));
        milblTitulo.setForeground(new java.awt.Color(47, 113, 148));
        milblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milblTitulo.setText(" BAJA DE CONTRATOS");
        getContentPane().add(milblTitulo);
        milblTitulo.setBounds(0, 50, 610, 40);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel11.setText("FIDEICOMITENTE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 100, 120, 30);

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox);
        jComboBox.setBounds(170, 100, 360, 30);

        jButton1.setText("Baja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 150, 60, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-625)/2, (screenSize.height-238)/2, 625, 238);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
}//GEN-LAST:event_jComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cliente = this.jComboBox.getSelectedItem().toString();
        if (!cliente.equals("   ---------------------Selecciona Fideicomitente---------------------   ")) {
            boolean seBorro = c.cancelaContrato(cliente);
            if (seBorro) {
                JOptionPane.showMessageDialog(this, "Operación realizada satisfactoriamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                this.jComboBox.setModel(new DefaultComboBoxModel(c.getClientes()));
                this.jComboBox.grabFocus();
            } else {
                JOptionPane.showMessageDialog(this, " Error almacenando información ", "Error", JOptionPane.ERROR_MESSAGE);
                this.jComboBox.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fideicomitente inválido, favor de verificar", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.jComboBox.grabFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new mntnBajaContratos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel milblTitulo;
    // End of variables declaration//GEN-END:variables
}
