package GestionContratos;

import javax.swing.*;
import java.util.Vector;
import Common.clsILookAndFeel;

/**
 *
 * @author SISTEMASGP
 */
public class rprtContratos extends javax.swing.JFrame {

    clsModelo c = new clsModelo();
    Vector datos = new Vector();
    String Encabezados[] = {" CLAVE CONTRATO ", " FIDEICOMITENTE ", " CUENTA ORIGEN ", " GRUPO ", " DOMICILIO FISCAL ", " RFC ", " TELÉFONO ", " E-MAIL ASESOR ",
        " TIPO HONORARIO ", " HONORARIO SIN IVA ", " OFICINAS ", " SALDO ", " ID_CODES "};
    clsIModeloTablaConsulta CheckList = new clsIModeloTablaConsulta(this.Encabezados, this.Encabezados.length);

    /** Creates new form rprtContratos */
    public rprtContratos() {
        initComponents();
        Vector tmp = c.getClientes();
        tmp.add("TODOS");
        this.jComboBox.setModel(new DefaultComboBoxModel(tmp));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mitbdatos = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Contratos ");
        getContentPane().setLayout(null);

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox);
        jComboBox.setBounds(150, 70, 380, 30);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("FIDEICOMITENTE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 70, 140, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de la Búsqueda"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        mitbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(mitbdatos);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 860, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 130, 880, 280);

        jToolBar2.setBackground(new java.awt.Color(202, 227, 127));
        jToolBar2.setBorder(new javax.swing.border.SoftBevelBorder(0, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(0, 0, 102));
        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar2.setPreferredSize(new java.awt.Dimension(500, 47));
        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(0, 0, 910, 40);

        setSize(new java.awt.Dimension(927, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed

        String cliente = this.jComboBox.getSelectedItem().toString();
        if (!cliente.equals("   ---------------------Selecciona Fideicomitente---------------------   ")) {
            datos = c.getInfoContrato(cliente);
            CheckList.setFila(datos);
            this.mitbdatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.mitbdatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            mitbdatos.setModel(CheckList);
        } else {
            JOptionPane.showMessageDialog(this, "Fideicomitente Inválido, Favor de Verificar", "Alerta", JOptionPane.ERROR_MESSAGE);
            this.jComboBox.grabFocus();
            datos = new Vector();
            CheckList.setFila(datos);
            this.mitbdatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.mitbdatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            mitbdatos.setModel(CheckList);
        }
    }//GEN-LAST:event_jComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new rprtContratos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable mitbdatos;
    // End of variables declaration//GEN-END:variables
}
