/*
 * clsGestionUsuarios.java
 * Created on 25/03/2011, 10:11:04 AM
 */
package GestionUsuarios;

import Common.clsILookAndFeel;

public class clsGestionUsuarios extends javax.swing.JFrame {

    /** Creates new form clsGestionUsuarios */
    public clsGestionUsuarios() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        mibtnAlta = new javax.swing.JButton();
        mibtnConsulta = new javax.swing.JButton();
        mibtnBaja = new javax.swing.JButton();
        milblTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Usuarios");
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(202, 227, 127));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(new javax.swing.border.SoftBevelBorder(0, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar2.setPreferredSize(new java.awt.Dimension(500, 47));

        mibtnAlta.setBackground(new java.awt.Color(255, 255, 255));
        mibtnAlta.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnAlta.setForeground(new java.awt.Color(255, 255, 255));
        mibtnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/alta_usuario.jpg"))); // NOI18N
        mibtnAlta.setToolTipText("Alta Usuario");
        mibtnAlta.setFocusPainted(false);
        mibtnAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnAlta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mibtnAlta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnAltaActionPerformed(evt);
            }
        });
        jToolBar2.add(mibtnAlta);

        mibtnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/consultaUsuario.jpg"))); // NOI18N
        mibtnConsulta.setToolTipText("Consulta Usuario");
        mibtnConsulta.setFocusable(false);
        mibtnConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnConsulta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnConsulta.setMaximumSize(new java.awt.Dimension(38, 38));
        mibtnConsulta.setMinimumSize(new java.awt.Dimension(38, 38));
        mibtnConsulta.setPreferredSize(new java.awt.Dimension(38, 38));
        mibtnConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mibtnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnConsultaActionPerformed(evt);
            }
        });
        jToolBar2.add(mibtnConsulta);

        mibtnBaja.setBackground(new java.awt.Color(255, 255, 255));
        mibtnBaja.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mibtnBaja.setForeground(new java.awt.Color(255, 255, 255));
        mibtnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/bajaUsuario.jpg"))); // NOI18N
        mibtnBaja.setToolTipText("Baja Usuario");
        mibtnBaja.setFocusPainted(false);
        mibtnBaja.setFocusable(false);
        mibtnBaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnBaja.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mibtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnBajaActionPerformed(evt);
            }
        });
        jToolBar2.add(mibtnBaja);

        jPanel2.add(jToolBar2);
        jToolBar2.setBounds(140, 80, 120, 40);

        milblTitulo1.setBackground(new java.awt.Color(0, 51, 153));
        milblTitulo1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        milblTitulo1.setForeground(new java.awt.Color(47, 113, 148));
        milblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milblTitulo1.setText("GESTIÓN DE USUARIOS");
        jPanel2.add(milblTitulo1);
        milblTitulo1.setBounds(0, 20, 370, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 370, 160);

        setSize(new java.awt.Dimension(384, 196));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mibtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnAltaActionPerformed
        new clsAltaUsuarios().show();
}//GEN-LAST:event_mibtnAltaActionPerformed

    private void mibtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnBajaActionPerformed
        new clsBajaUsuarios().show();
    }//GEN-LAST:event_mibtnBajaActionPerformed

    private void mibtnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnConsultaActionPerformed
        new clsConsultaUsuarios().show();
    }//GEN-LAST:event_mibtnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new clsGestionUsuarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton mibtnAlta;
    private javax.swing.JButton mibtnBaja;
    private javax.swing.JButton mibtnConsulta;
    private javax.swing.JLabel milblTitulo1;
    // End of variables declaration//GEN-END:variables
}
