/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gestionCuentas.java
 * Autor : Hernández Paredes Denis Alin
 * Created on 18/04/2011, 03:59:49 PM
 */
package GestionCuentasBancarias;

import Common.clsILookAndFeel;

public class gestionCuentas extends javax.swing.JFrame {

    /** Creates new form gestionCuentas */
    public gestionCuentas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        mibtnAlta = new javax.swing.JButton();
        mibtnBaja = new javax.swing.JButton();
        mibtnSalir = new javax.swing.JButton();
        mibtnReporte = new javax.swing.JButton();
        milblTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Cuentas Bancarias");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(202, 227, 127));
        jPanel1.setLayout(null);

        jToolBar3.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar3.setFloatable(false);
        jToolBar3.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar3.setRollover(true);
        jToolBar3.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar3.setPreferredSize(new java.awt.Dimension(500, 47));

        mibtnAlta.setBackground(new java.awt.Color(255, 255, 255));
        mibtnAlta.setFont(new java.awt.Font("Century Gothic", 0, 12));
        mibtnAlta.setForeground(new java.awt.Color(255, 255, 255));
        mibtnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/alta_bank.jpg"))); // NOI18N
        mibtnAlta.setToolTipText("Alta de Cuentas");
        mibtnAlta.setFocusPainted(false);
        mibtnAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnAlta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mibtnAlta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnAltaActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnAlta);

        mibtnBaja.setBackground(new java.awt.Color(255, 255, 255));
        mibtnBaja.setFont(new java.awt.Font("Century Gothic", 0, 12));
        mibtnBaja.setForeground(new java.awt.Color(255, 255, 255));
        mibtnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/baja_bank.jpg"))); // NOI18N
        mibtnBaja.setToolTipText("Baja de Cuentas");
        mibtnBaja.setFocusPainted(false);
        mibtnBaja.setFocusable(false);
        mibtnBaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnBaja.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mibtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnBajaActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnBaja);

        mibtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        mibtnSalir.setFont(new java.awt.Font("Century Gothic", 0, 12));
        mibtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        mibtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/modificar.jpg"))); // NOI18N
        mibtnSalir.setToolTipText("Modificar de Cuentas");
        mibtnSalir.setFocusPainted(false);
        mibtnSalir.setFocusable(false);
        mibtnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mibtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnSalir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnSalirActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnSalir);

        mibtnReporte.setBackground(new java.awt.Color(255, 255, 255));
        mibtnReporte.setFont(new java.awt.Font("Century Gothic", 0, 12));
        mibtnReporte.setForeground(new java.awt.Color(255, 255, 255));
        mibtnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Tabla.jpg"))); // NOI18N
        mibtnReporte.setToolTipText("Consulta de Cuentas");
        mibtnReporte.setFocusable(false);
        mibtnReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        mibtnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mibtnReporte.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mibtnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mibtnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibtnReporteActionPerformed(evt);
            }
        });
        jToolBar3.add(mibtnReporte);

        jPanel1.add(jToolBar3);
        jToolBar3.setBounds(140, 90, 160, 40);

        milblTitulo1.setBackground(new java.awt.Color(153, 153, 255));
        milblTitulo1.setFont(new java.awt.Font("Trebuchet MS", 1, 22));
        milblTitulo1.setForeground(new java.awt.Color(47, 113, 148));
        milblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milblTitulo1.setText("ADMINISTRACIÓN DE CUENTAS BANCARIAS");
        jPanel1.add(milblTitulo1);
        milblTitulo1.setBounds(0, 30, 450, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 180);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-464)/2, (screenSize.height-218)/2, 464, 218);
    }// </editor-fold>//GEN-END:initComponents

    private void mibtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnAltaActionPerformed
        new mntnAltaCuentas().show();
    }//GEN-LAST:event_mibtnAltaActionPerformed

    private void mibtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnBajaActionPerformed
        new mntnBajaCuentas().show();
}//GEN-LAST:event_mibtnBajaActionPerformed

    private void mibtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnSalirActionPerformed
        new mntnModificacionCuentas().show();
}//GEN-LAST:event_mibtnSalirActionPerformed

    private void mibtnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibtnReporteActionPerformed
        new rprtCuentas().show();
}//GEN-LAST:event_mibtnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new gestionCuentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JButton mibtnAlta;
    private javax.swing.JButton mibtnBaja;
    private javax.swing.JButton mibtnReporte;
    private javax.swing.JButton mibtnSalir;
    private javax.swing.JLabel milblTitulo1;
    // End of variables declaration//GEN-END:variables
}
