/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mntnAltaCuentas.java
 * Autor : Hernández Paredes Denis Alin
 * Created on 18/04/2011, 04:24:58 PM
 */
package GestionCuentasBancarias;

import javax.swing.*;
import Common.clsILookAndFeel;

public class mntnAltaCuentas extends javax.swing.JFrame {

    clsModelo c = new clsModelo();
    String status = "";

    /** Creates new form mntnAltaCuentas */
    public mntnAltaCuentas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mitxtCuentaOrigen = new javax.swing.JTextField();
        mitxtNumCuenta = new javax.swing.JTextField();
        mitxtClaveCuenta = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        milblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Cuentas Bancarias");
        getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel15.setText("CLABE DE CUENTA");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 160, 140, 30);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel16.setText("CUENTA DE ORIGEN");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 100, 140, 30);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel17.setText("NÚMERO DE CUENTA");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(50, 130, 150, 30);

        mitxtCuentaOrigen.setFont(new java.awt.Font("Tahoma", 1, 14));
        mitxtCuentaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtCuentaOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(mitxtCuentaOrigen);
        mitxtCuentaOrigen.setBounds(200, 100, 220, 30);

        mitxtNumCuenta.setFont(new java.awt.Font("Tahoma", 1, 14));
        mitxtNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtNumCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(mitxtNumCuenta);
        mitxtNumCuenta.setBounds(200, 130, 220, 30);

        mitxtClaveCuenta.setFont(new java.awt.Font("Tahoma", 1, 14));
        mitxtClaveCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitxtClaveCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(mitxtClaveCuenta);
        mitxtClaveCuenta.setBounds(200, 160, 220, 30);

        jButton.setText("Guardar");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        jButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonKeyPressed(evt);
            }
        });
        getContentPane().add(jButton);
        jButton.setBounds(200, 220, 80, 23);

        jToolBar2.setBackground(new java.awt.Color(202, 227, 127));
        jToolBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(0, 0, 102));
        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar2.setPreferredSize(new java.awt.Dimension(500, 47));
        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(0, 0, 460, 40);

        milblTitulo.setBackground(new java.awt.Color(0, 51, 153));
        milblTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 21));
        milblTitulo.setForeground(new java.awt.Color(47, 113, 148));
        milblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milblTitulo.setText("ALTA DE CUENTAS");
        getContentPane().add(milblTitulo);
        milblTitulo.setBounds(0, 50, 460, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-476)/2, (screenSize.height-308)/2, 476, 308);
    }// </editor-fold>//GEN-END:initComponents

    public void Limpia() {
        this.mitxtCuentaOrigen.setText("");
        this.mitxtNumCuenta.setText("");
        this.mitxtClaveCuenta.setText("");
        this.mitxtCuentaOrigen.grabFocus();
    }

    private void mitxtCuentaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtCuentaOrigenActionPerformed
        String cuenta_origen = mitxtCuentaOrigen.getText().toUpperCase().toString().trim();
        String valida_cuenta = c.validaCuenta(cuenta_origen);
        this.status = valida_cuenta;

        if (valida_cuenta.equals("")) {
            this.mitxtNumCuenta.grabFocus();
        } else {
            if (valida_cuenta.equals("A")) {
                JOptionPane.showMessageDialog(this, " Cuenta existente, favor de verificar ", "Alerta", JOptionPane.WARNING_MESSAGE);
                this.mitxtCuentaOrigen.setText("");
                this.mitxtCuentaOrigen.grabFocus();
            } else {
                this.mitxtNumCuenta.grabFocus();
            }
        }
}//GEN-LAST:event_mitxtCuentaOrigenActionPerformed

    private void mitxtNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtNumCuentaActionPerformed
        String num_cuenta = mitxtNumCuenta.getText().toUpperCase().toString().trim();
        Double tmp = 0.0D;
        try {
            tmp = Double.parseDouble(num_cuenta);
            if (tmp > 0.0) {
                if (num_cuenta.length() == 13) {
                    mitxtClaveCuenta.grabFocus();
                } else {
                    JOptionPane.showMessageDialog(this, " El número de cuenta debe ser de 13 dígitos  ", "Alerta", JOptionPane.WARNING_MESSAGE);
                    mitxtNumCuenta.setText("");
                    mitxtNumCuenta.grabFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, " El número de cuenta debe ser mayor a 0  ", "Alerta", JOptionPane.WARNING_MESSAGE);
                mitxtNumCuenta.setText("");
                mitxtNumCuenta.grabFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Formato inválido ", "Error", JOptionPane.ERROR_MESSAGE);
            mitxtNumCuenta.setText("");
            mitxtNumCuenta.grabFocus();
        }
}//GEN-LAST:event_mitxtNumCuentaActionPerformed

    private void mitxtClaveCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitxtClaveCuentaActionPerformed
        String num_cuenta = mitxtClaveCuenta.getText().toUpperCase().toString().trim();
        Double tmp = 0.0D;
        try {
            tmp = Double.parseDouble(num_cuenta);
            if (tmp > 0.0) {
                jButton.grabFocus();
            } else {
                JOptionPane.showMessageDialog(this, " La clave de cuenta debe ser mayor a 0  ", "Alerta", JOptionPane.WARNING_MESSAGE);
                mitxtClaveCuenta.setText("");
                mitxtClaveCuenta.grabFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " El formato de la clave de cuenta es inválido ", "Error", JOptionPane.ERROR_MESSAGE);
            mitxtClaveCuenta.setText("");
            mitxtClaveCuenta.grabFocus();
        }
}//GEN-LAST:event_mitxtClaveCuentaActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        String cuenta_origen = this.mitxtCuentaOrigen.getText().toUpperCase().toString().trim();
        String num_cuenta = this.mitxtNumCuenta.getText().toString().trim();
        String clave_cuenta = this.mitxtClaveCuenta.getText().toString().trim();
        boolean guarda = false;
        if (!cuenta_origen.equals("") && !num_cuenta.equals("") && !clave_cuenta.equals("")) {
            guarda = c.guardaCuenta(cuenta_origen, num_cuenta, clave_cuenta, status);
            if (guarda) {
                JOptionPane.showMessageDialog(this, " Operación realizada satisfactoriamente ", "Información", JOptionPane.INFORMATION_MESSAGE);
                Limpia();
            } else {
                JOptionPane.showMessageDialog(this, " Error almacenando información ", "Error", JOptionPane.ERROR_MESSAGE);
                Limpia();
            }
        } else {
            JOptionPane.showMessageDialog(this, " Información incompleta ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.mitxtCuentaOrigen.grabFocus();
        }
    }//GEN-LAST:event_jButtonActionPerformed

    private void jButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonKeyPressed
        String cuenta_origen = this.mitxtCuentaOrigen.getText().toUpperCase().toString().trim();
        String num_cuenta = this.mitxtNumCuenta.getText().toString().trim();
        String clave_cuenta = this.mitxtClaveCuenta.getText().toString().trim();
        boolean guarda = false;
        if (!cuenta_origen.equals("") && !num_cuenta.equals("") && !clave_cuenta.equals("")) {
            guarda = c.guardaCuenta(cuenta_origen, num_cuenta, clave_cuenta, status);
            if (guarda) {
                JOptionPane.showMessageDialog(this, " Operación realizada satisfactoriamente ", "Información", JOptionPane.INFORMATION_MESSAGE);
                Limpia();
            } else {
                JOptionPane.showMessageDialog(this, " Error almacenando información ", "Error", JOptionPane.ERROR_MESSAGE);
                Limpia();
            }
        } else {
            JOptionPane.showMessageDialog(this, " Información incompleta ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.mitxtCuentaOrigen.grabFocus();
        }
    }//GEN-LAST:event_jButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new mntnAltaCuentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel milblTitulo;
    private javax.swing.JTextField mitxtClaveCuenta;
    private javax.swing.JTextField mitxtCuentaOrigen;
    private javax.swing.JTextField mitxtNumCuenta;
    // End of variables declaration//GEN-END:variables
}
