/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mntnBajaCuentas.java
 *Autor : Hernández Paredes Denis Alin
 * Created on 18/04/2011, 04:25:41 PM
 */
package GestionCuentasBancarias;

import javax.swing.*;
import Common.clsILookAndFeel;
import java.util.Vector;

public class mntnBajaCuentas extends javax.swing.JFrame {

    clsModelo c = new clsModelo();

    /** Creates new form mntnBajaCuentas */
    public mntnBajaCuentas() {
        initComponents();
        Vector cuentas = c.getCuentasOrigen();
        this.jComboBox.setModel(new DefaultComboBoxModel(cuentas));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        jToolBar2 = new javax.swing.JToolBar();
        milblTitulo = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja de Cuentas Bancarias");
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel11.setText("CUENTA DE ORIGEN");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 110, 140, 30);

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox);
        jComboBox.setBounds(200, 110, 180, 30);

        jToolBar2.setBackground(new java.awt.Color(202, 227, 127));
        jToolBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(0, 0, 102));
        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar2.setPreferredSize(new java.awt.Dimension(500, 47));
        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(0, 0, 440, 40);

        milblTitulo.setBackground(new java.awt.Color(0, 51, 153));
        milblTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 21));
        milblTitulo.setForeground(new java.awt.Color(47, 113, 148));
        milblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milblTitulo.setText("BAJA DE CUENTAS");
        getContentPane().add(milblTitulo);
        milblTitulo.setBounds(0, 50, 440, 40);

        jButton.setText("Baja");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton);
        jButton.setBounds(190, 160, 80, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-456)/2, (screenSize.height-269)/2, 456, 269);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        this.jButton.grabFocus();
}//GEN-LAST:event_jComboBoxActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        String cuenta_origen = jComboBox.getSelectedItem().toString();
        if (!cuenta_origen.equals("   -----Selecciona Cuenta-----   ")) {
            boolean baja = c.cancelaCuenta(cuenta_origen);
            if (baja) {
                JOptionPane.showMessageDialog(this, " Operación realizada satisfactoriamente ", "Información", JOptionPane.INFORMATION_MESSAGE);
                this.jComboBox.setModel(new DefaultComboBoxModel(c.getCuentasOrigen()));
                this.jComboBox.grabFocus();
            } else {
                JOptionPane.showMessageDialog(this, " Error actualizando información ", "Error", JOptionPane.ERROR_MESSAGE);
                this.jComboBox.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, " Favor de especificar una cuenta ", "Alerta", JOptionPane.WARNING_MESSAGE);
            this.jComboBox.grabFocus();
        }

    }//GEN-LAST:event_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new mntnBajaCuentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel milblTitulo;
    // End of variables declaration//GEN-END:variables
}
