/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rprtCuentas.java
 * Autor : Hernández Paredes Denis Alin
 * Created on 18/04/2011, 04:26:50 PM
 */
package GestionCuentasBancarias;

import javax.swing.*;
import java.util.Vector;
import Common.clsILookAndFeel;

public class rprtCuentas extends javax.swing.JFrame {

    clsModelo c = new clsModelo();
    Vector datos = new Vector();
    String Encabezados[] = {" CUENTA DE ORIGEN ", " NÚMERO DE CUENTA ", " CLABE DE CUENTA "};
    clsIModeloTablaConsulta CheckList = new clsIModeloTablaConsulta(this.Encabezados, this.Encabezados.length);

    /** Creates new form rprtCuentas */
    public rprtCuentas() {
        initComponents();
        Vector cuentas = c.getCuentasOrigen();
        cuentas.add("TODOS");
        this.jComboBox.setModel(new DefaultComboBoxModel(cuentas));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        milblTitulo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mitbdatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Cuentas Bancarias");
        getContentPane().setLayout(null);

        jToolBar2.setBackground(new java.awt.Color(202, 227, 127));
        jToolBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 204, 255)));
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(0, 0, 102));
        jToolBar2.setRollover(true);
        jToolBar2.setMinimumSize(new java.awt.Dimension(200, 47));
        jToolBar2.setPreferredSize(new java.awt.Dimension(500, 47));
        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(0, 0, 570, 40);

        milblTitulo.setBackground(new java.awt.Color(0, 51, 153));
        milblTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        milblTitulo.setForeground(new java.awt.Color(47, 113, 148));
        milblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milblTitulo.setText("CUENTAS BANCARIAS");
        getContentPane().add(milblTitulo);
        milblTitulo.setBounds(0, 60, 550, 40);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel11.setText("CUENTA DE ORIGEN");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 120, 140, 30);

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox);
        jComboBox.setBounds(200, 120, 180, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de la Búsqueda"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        mitbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(mitbdatos);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 520, 170);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 170, 540, 200);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-572)/2, (screenSize.height-420)/2, 572, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        String cuenta_origen = jComboBox.getSelectedItem().toString();
        if (!cuenta_origen.equals("   -----Selecciona Cuenta-----   ")) {
            datos = c.getInfoCuentas(cuenta_origen);
            CheckList.setFila(datos);
            this.mitbdatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.mitbdatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            mitbdatos.setModel(CheckList);
        } else {
            datos = new Vector();
            CheckList.setFila(datos);
            this.mitbdatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.mitbdatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            mitbdatos.setModel(CheckList);
            JOptionPane.showMessageDialog(this, " Favor de Seleccionar una Cuenta Válida ", "Error", JOptionPane.ERROR_MESSAGE);

        }
}//GEN-LAST:event_jComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                clsILookAndFeel.setSystemLookAndFell();
                new rprtCuentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel milblTitulo;
    private javax.swing.JTable mitbdatos;
    // End of variables declaration//GEN-END:variables
}
